server:
  discovery:
    host: 192.168.8.65
    prot: 8761
  rabbit:
    host: 192.168.8.65
    port: 5672
    username: rabbitadmin
    password: 123456
    virtual-host: /

eureka:
  instance:
    appname: config
    metadata-map:
      cluster: lbd-cluster
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${server.discovery.host}:${server.discovery.port}/eureka/