server:
  port: 8888

eureka:
  instance:
    appname: config
    metadata-map:
      cluster: lbd-cluster
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.8.39:8761/eureka/

spring:
  rabbitmq:
    host: 192.168.8.38
    port: 5672
    username: rabbitadmin
    password: 123456
    virtual-host: /