server:
  port: 9092

swagger:
  package: com.lbd.cloud.service.crawler.controller
  title: 数据采集
  description: 数据采集微服务
  termsOfServiceUrl: https://github.com/MoreDo
  contact:
    name: MoreDo
    url: https://github.com/MoreDo
    email: 419092109@qq.com
  version: 1.0

spring:
  http:
    encoding:
      charset: UTF-8
      enable: true
      force: true
    multipart:
      max-file-size: 4Mb
  zipkin:
    base-url: http://192.168.8.65:7411
    enabled: true
  data:
    mongodb:
      host: 192.168.8.65
      port: 27017
      database: crawler
      username: crawler
      password: 123456
  cloud:
    stream:
      defaultBinder: defaultRabbit
      bindings:
        stockout-callback:
          destination: stockout-callback
          group: crawler
      binders:
        defaultRabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 192.168.8.65
                port: 5672
                username: rabbitadmin
                password: 123456
                virtual-host: /
  rabbitmq:
    host: 192.168.8.65
    port: 5672
    username: rabbitadmin
    password: 123456
    virtual-host: /
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.8.65:8761/eureka/
  instance:
    appname: crawler
    metadata-map:
      cluster: lbd-cluster
    prefer-ip-address: false

#服务器获取地址
lbd:
  #代理服务器获取地址
  proxy:
     #开心代理服务器获取地址
    kaixin:
      bind: http://s.kxdaili.com/StApiEditIP.html?u=LBD3127&p=x147159&api=201709201502467466
      url: http://s.kxdaili.com/?api=201709201502467466&count=100&fitter=1&px=2
      #间隔时间（秒）
      interval: 10
      #有效期（分钟），0为长期
      validity: 2
      bean: KAIXIN_PROXY
#    xicidaili:
#      url: http://www.xicidaili.com/nn
#      interval: 60
#      validity: 0
#      bean: XICIDAILI_PROXY

security:
  oauth2:
    client:
      accessTokenUri: http://192.168.8.66:10000/uua/oauth/token
      userAuthorizationUri: http://192.168.8.66:10000/uua/oauth/authorize
      clientId: crawler
      clientSecret: crawler2017
    resource:
      token-info-uri: http://192.168.8.66:10000/uua/oauth/check_token
      prefer-token-info: true
      user-info-uri: http://192.168.8.66:10000/uua/user
      id: crawler