server:
  port: 9070

swagger:
  package: com.lbd.cloud.service.message.controller
  title: 消息系统
  description: 消息系统微服务
  termsOfServiceUrl: https://github.com/MoreDo
  contact:
    name: MoreDo
    url: https://github.com/MoreDo
    email: 419092109@qq.com
  version: 1.0

spring:
  zipkin:
    base-url: http://192.168.8.65:7411
    enabled: false
  datasource:
    url: jdbc:mysql://192.168.8.20:3306/message?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&useOldAliasMetadataBehavior=true
    username: root
    password: 123456
    max-active: 20
    max-idle: 8
    min-idle: 8
    initial-size: 10
    #指定连接多久没被使用时，被设置为空闲，默认为10ms
    idle-timeout: 10
    driver-class-name: com.mysql.jdbc.Driver
    #验证连接的有效性
    test-while-idle: true
    validation-query: select 1 from dual
    #空闲连接回收的时间间隔，与test-while-idle一起使用，设置5分钟
    time-between-eviction-runs-millis: 300000
    #连接池空闲连接的有效时间 ，设置30分钟
    min-evictable-idle-time-millis: 1800000
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.8.65:8761/eureka/
  instance:
    appname: message
    metadata-map:
      cluster: lbd-cluster

security:
  oauth2:
    client:
      accessTokenUri: http://192.168.8.66:10000/uua/oauth/token
      userAuthorizationUri: http://192.168.8.66:10000/uua/oauth/authorize
      clientId: message
      clientSecret: message2017
    resource:
      token-info-uri: http://192.168.8.66:10000/uua/oauth/check_token
      prefer-token-info: true
      user-info-uri: http://192.168.8.66:10000/uua/user
      id: message