server:
  port: 9080

swagger:
  package: com.lbd.cloud.service.risk.controller
  title: 风险管理
  description: 风险管理微服务
  termsOfServiceUrl: https://github.com/MoreDo
  contact:
    name: MoreDo
    url: https://github.com/MoreDo
    email: 419092109@qq.com
  version: 1.0

spring:
  http:
    encoding:
      charset: UTF-8
      enable: true
      force: true
  zipkin:
    base-url: http://192.168.8.39:7411
    enabled: true
  datasource:
    url: jdbc:mysql://192.168.8.39:3306/risk?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&useOldAliasMetadataBehavior=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    max-active: 20
    max-idle: 8
    min-idle: 8
    initial-size: 10
    #指定连接多久没被使用时，被设置为空闲，默认为10ms
    idle-timeout: 10
    #验证连接的有效性
    test-while-idle: true
    validation-query: select 1 from dual
    #空闲连接回收的时间间隔，与test-while-idle一起使用，设置5分钟
    time-between-eviction-runs-millis: 300000
    #连接池空闲连接的有效时间 ，设置30分钟
    min-evictable-idle-time-millis: 1800000
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
  cloud:
    stream:
      defaultBinder: defaultRabbit
      bindings:
        #订阅发现缺货消息
        stockout:
          destination: stockout
          group: risk
        #发送风险词监测消息
        risk_words-monitor:
          destination: risk_words-monitor
        #订阅风险词监测回调消息
        risk_words-monitor-callback:
          destination: risk_words-monitor-callback
          group: risk
        #发送风险词处理消息
        risk_words-process:
          destination: risk_words-process
        #订阅风险词处理回调消息
        risk_words-process-callback:
          destination: risk_words-process-callback
          group: risk
        #发送源店铺过滤监测消息
        filter_store-monitor:
          destination: filter_store-monitor
        #订阅源店铺过滤监测回调消息
        filter_store-monitor-callback:
          destination: filter_store-monitor-callback
          group: risk
        #发送源店铺过滤处理消息
        filter_store-process:
          destination: filter_store-process
        #订阅源店铺过滤处理回调消息
        filter_store-process-callback:
          destination: filter_store-process-callback
          group: risk
      binders:
        defaultRabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 192.168.8.38
                port: 5672
                username: rabbitadmin
                password: 123456
                virtual-host: /
  rabbitmq:
    host: 192.168.8.38
    port: 5672
    username: rabbitadmin
    password: 123456
    virtual-host: /
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.8.39:8761/eureka/
  instance:
    appname: risk
    metadata-map:
      cluster: lbd-cluster
    prefer-ip-address: false

feign:
  hystrix:
    enabled: true

security:
  oauth2:
    client:
      accessTokenUri: http://192.168.8.39:10000/uua/oauth/token
      userAuthorizationUri: http://192.168.8.39:10000/uua/oauth/authorize
      clientId: risk
      clientSecret: risk2017
    resource:
      token-info-uri: http://192.168.8.39:10000/uua/oauth/check_token
      prefer-token-info: true
      user-info-uri: http://192.168.8.39:10000/uua/user
      id: risk