server:
  port: 7020

eureka:
  client:
    service-url:
      defaultZone: http://192.168.8.39:8761/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    appname: spring-boot-admin
    metadata-map:
      cluster: lbd-cluster
    lease-renewal-interval-in-seconds: 10

spring:
  boot:
    admin:
      turbine:
        url: http://192.168.8.39:7090/turbine.stream
        clusters: lbd-cluster